# Setup
title: Sharky7pb的博客
description: 道阻且长，行之将至。
url: https://github.com/sharky7pb/blogpb.github.io
avatar: /pic1.jpeg
paginate: 5
permalink: pretty
cover_image: /back.jpeg
baseurl: "/blog" # the subpath of your site, e.g. /blog
# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Sharky7pb
  card: summary
logo: logo.png
social:
  name: Sharky7pb
  links:
    - https://github.com/sharky7pb
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Sharky7pb
  url: https://github.com/sharky7pb
  email: 1821984081@qq.com

include: [_layouts,_data,_includes,_posts,_sass]
